#!/usr/bin/env python2
import os
import json
import sys

if len(sys.argv) > 1:
    specific_chain = sys.argv[1]
else:
    specific_chain = False

def format_param(param, value):
    return '-' + param + '=' + value

script_dir = os.getenv('HOME')
with open(os.getenv('HOME') + '/komodo/src/assetchains.json') as file:
    assetchains = json.load(file)

    for chain in assetchains:
        if chain['ac_name'] in ['BEER', 'PIZZA', 'VOTE2018']:
            continue
        if specific_chain and chain['ac_name'] != specific_chain:
            continue
        params = []
        for param, value in chain.items():
            if isinstance(value, list):
                for dupe_value in value:
                    params.append(format_param(param, dupe_value))
            else:
                params.append(format_param(param, value))
        print(' '.join(params))
