#!/usr/bin/env python2
import os
import json

script_dir = os.getenv('HOME')
with open(os.getenv('HOME') + '/komodo/src/assetchains.json') as file:
    assetchains = json.load(file)

for chain in assetchains:
    if chain['ac_name'] in ['BEER', 'PIZZA', 'VOTE2018']:
        continue
    print(chain['ac_name'])
