#!/usr/bin/env python2
import os
import json
import sys

if len(sys.argv) >= 2:
    specific_chain = sys.argv[1]
else:
    specific_chain = 0

def format_param(param, value):
    return '-' + param + '=' + value

script_dir = os.path.dirname(__file__)
with open(script_dir + '/assetchains.json') as file:
    assetchains = json.load(file)

    for chain in assetchains:
        if specific_chain != 0 and chain["ac_name"] != specific_chain:
            continue
        params = []
        for param, value in chain.items():
            if isinstance(value, list):
                for dupe_value in value:
                    params.append(format_param(param, dupe_value))
            else:
                params.append(format_param(param, value))
        print(' '.join(params))
